name: 'Setup Q CLI'
description: 'Install and cache Amazon Q Developer CLI for GitHub Actions workflows'
author: 'Hugues Clouâtre'

inputs:
  version:
    description: 'Q CLI version to install (e.g., latest)'
    required: false
    default: 'latest'
  aws-region:
    description: 'AWS region for Q CLI operations'
    required: false
    default: 'us-east-1'
  enable-sigv4:
    description: 'Enable SIGV4 authentication mode'
    required: false
    default: 'false'
  verify-checksum:
    description: 'Verify SHA256 checksum of downloaded binary'
    required: false
    default: 'false'

outputs:
  q-version:
    description: 'Installed Q CLI version'
    value: ${{ steps.install.outputs.version }}
  q-path:
    description: 'Path to Q CLI binary directory'
    value: ${{ steps.setup-path.outputs.path }}

runs:
  using: 'composite'
  steps:
    - name: Check platform support
      shell: bash
      run: |
        OS="${{ runner.os }}"
        if [ "$OS" != "Linux" ]; then
          echo "::error::Q CLI action only supports Linux runners. macOS binaries are not available via AWS CDN."
          exit 1
        fi

    - name: Cache Q CLI binaries
      id: cache-q
      uses: actions/cache@v4
      with:
        path: ~/.local/bin/qchat
        key: q-${{ inputs.version }}-${{ runner.os }}-${{ runner.arch }}

    - name: Install Q CLI
      id: install
      if: steps.cache-q.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "::group::Installing Q CLI ${{ inputs.version }}"
        mkdir -p ~/.local/bin
        
        # Determine architecture
        ARCH="${{ runner.arch }}"
        if [ "$ARCH" = "X64" ]; then
          Q_ARCH="x86_64"
        elif [ "$ARCH" = "ARM64" ]; then
          Q_ARCH="aarch64"
        else
          echo "::error::Unsupported architecture: $ARCH"
          exit 1
        fi
        
        # AWS CDN expects version without 'v' prefix (e.g., '1.19.6' not 'v1.19.6')
        VERSION="${{ inputs.version }}"
        # Strip 'v' prefix if present
        VERSION="${VERSION#v}"
        
        # Download URL (Linux only)
        DOWNLOAD_URL="https://desktop-release.q.us-east-1.amazonaws.com/${VERSION}/q-${Q_ARCH}-linux.zip"
        echo "Downloading from: $DOWNLOAD_URL"
        
        # Download and extract
        curl --proto '=https' --tlsv1.2 -sSfL "$DOWNLOAD_URL" -o q.zip
        
        # Verify checksum if requested
        if [ "${{ inputs.verify-checksum }}" = "true" ]; then
          echo "Downloading SHA256 checksum..."
          curl --proto '=https' --tlsv1.2 -sSfL "${DOWNLOAD_URL}.sha256" -o q.zip.sha256
          
          EXPECTED_SHA=$(cat q.zip.sha256)
          ACTUAL_SHA=$(shasum -a 256 q.zip | cut -d' ' -f1)
          
          if [ "$EXPECTED_SHA" != "$ACTUAL_SHA" ]; then
            echo "::error::SHA256 mismatch! Expected: $EXPECTED_SHA, Got: $ACTUAL_SHA"
            exit 1
          fi
          echo "SHA256 verification passed"
        fi
        
        unzip -q q.zip
        
        # Get actual version from BUILD-INFO if available
        if [ -f q/BUILD-INFO ]; then
          ACTUAL_VERSION=$(grep '^BUILD_VERSION=' q/BUILD-INFO | cut -d= -f2)
          echo "version=${ACTUAL_VERSION}" >> $GITHUB_OUTPUT
        else
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
        fi
        
        # Copy only qchat binary (sufficient for CI/CD)
        cp q/bin/qchat ~/.local/bin/
        chmod +x ~/.local/bin/qchat
        
        # Cleanup
        rm -rf q q.zip
        
        echo "::endgroup::"

    - name: Setup PATH
      id: setup-path
      shell: bash
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "path=$HOME/.local/bin" >> $GITHUB_OUTPUT

    - name: Configure SIGV4 authentication
      if: inputs.enable-sigv4 == 'true'
      shell: bash
      run: |
        echo "AMAZON_Q_SIGV4=true" >> $GITHUB_ENV
        echo "AWS_REGION=${{ inputs.aws-region }}" >> $GITHUB_ENV

    - name: Verify installation
      shell: bash
      run: |
        echo "::group::Verifying Q CLI installation"
        qchat --version
        echo "Installed binary:"
        ls -lh ~/.local/bin/qchat
        echo "::endgroup::"

branding:
  icon: 'terminal'
  color: 'orange'
